site_name: Roydad  # 网页显示名称
docs_dir: github.io.md # 发布的笔记文件夹相对路径
copyright: Roydad # 网页底部信息
theme:
  logo: assets/icon.jpeg 
       # 主页logo
  favicon: assets/icon.jpeg   # 浏览器标签页上的小Logo

#以下部分固定不用修改
  name: material
  language: zh
  palette:
    scheme: slate
    primary: black

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:

  - search:
      separator: '[\s\u200b\-]'
extra:
  generator: false

#extra_javascript:
  #- javascripts/mathjax.js
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js




